CREATE TABLE orders_product(
    orders_product_id INT generated by default as identity (start with 15) NOT NULL,
    orders_id INT NOT NULL,
    product_id INT NOT NULL,
    product_quantity INT NOT NULL,
    PRIMARY KEY(orders_product_id),
    CONSTRAINT orders_fkey FOREIGN KEY(orders_id) REFERENCES orders(orders_id),
    CONSTRAINT product_orders_fkey FOREIGN KEY(product_id) REFERENCES product(product_id)
)