CREATE TABLE cart_product(
    cart_product_id INT generated by default as identity (start with 15) NOT NULL,
    cart_id INT NOT NULL,
    product_id INT NOT NULL,
    product_quantity INT NOT NULL,
    PRIMARY KEY(cart_product_id),
    CONSTRAINT cart_fkey FOREIGN KEY(cart_id) REFERENCES cart(cart_id),
    CONSTRAINT product_fkey FOREIGN KEY(product_id) REFERENCES product(product_id)
)