insert into category(category_id, category_name) values(1, 'Kitchen');
insert into category(category_id, category_name) values(2, 'Bathroom');
insert into category(category_id, category_name) values(3, 'Tools');
insert into category(category_id, category_name) values(4, 'Flooring');
insert into category(category_id, category_name) values(5, 'Grills');
insert into category(category_id, category_name) values(6, 'Appliances');
insert into category(category_id, category_name) values(7, 'Lighting and Ceiling Fan');
insert into category(category_id, category_name) values(8, 'Paint');
insert into category(category_id, category_name) values(9, 'Lawn and Garden');
insert into category(category_id, category_name) values(10, 'Patio');