CREATE TABLE customer(
    customer_id INT generated by default as identity (start with 15) NOT NULL,
    customer_name VARCHAR(200) NOT NULL,
    customer_mob_no varchar(10) NOT NULL,
    customer_email VARCHAR(200) NOT NULL,
    customer_address VARCHAR(200) NOT NULL,
    cart_id INT NOT NULL,
    orders_id INT NOT NULL,
    PRIMARY KEY(customer_id),
    CONSTRAINT customer_cart_f_key FOREIGN KEY(cart_id) REFERENCES cart(cart_id),
    CONSTRAINT customer_orders_f_key FOREIGN KEY(orders_id) REFERENCES orders(orders_id)
)